---
widget: { class: widget }
sizer: { type: horizontal, gap: 0 }
children:
- widget: { class: scrollBarPane }
  children:
  - widget: 
      class: list
      id: "assetList"
      size: [250, 20]
      options:
      - id: test0
        text: test
      - id: test1
        text: test
      - id: test2
        text: test
- widget: { class: label, text: "TODO :)" }
  fill: centre
  proportion: 1
...