---
widget: { class: image, image: "ui/title_capsule.png", innerBorder: [ 4, 1, 4, 4 ], colour: "#9C5BB5" }
sizer: { type: vertical }
children:
- widget: { id: componentType, class: label, text: "Name" }
  fill: centre
- widget: { id: componentFields, class: widget }
  border: [0, 3, 0, 1]
  sizer: { type: grid, gap: 2, columns: 2 }
...