---
widget: { class: widget }
sizer: { type: vertical }
children:
- sizer: { type: horizontal }
  children:
  - widget: { id: saveButton, class: button, text: "Save", size: [100, 30] }
- sizer: { type: horizontal }
  proportion: 1
  children:
  - widget: { id: scrollBarPane, class: scrollBarPane, scrollHorizontal: true, scrollVertical: true, size: [350, 30] }
    sizer: { type: vertical }
    children:
    - widget: { id: entityList, class: entityList }
      proportion: 1
  - widget: { id: canvas, class: sceneEditorCanvas }
    proportion: 1
  - widget: { id: entityEditor, class: entityEditor }
...