---
widget: { class: widget }
sizer: { type: vertical }
children:
- sizer: { type: horizontal }
  children:
  - widget: { id: saveButton, class: button, text: "Save", size: [100, 30] }
- sizer: { type: horizontal }
  proportion: 1
  children:
  - sizer: { type: vertical }
    children:
    - widget: { id: scrollBarPane, class: scrollBarPane, scrollHorizontal: true, scrollVertical: true, size: [350, 30] }
      sizer: { type: vertical }
      proportion: 1
      children:
      - widget: { id: entityList, class: entityList }
        proportion: 1
    - sizer: { type: horizontal }
      children:
      - widget: { id: addEntity, class: button, text: Add Entity }
        proportion: 1
      - widget: { id: addPrefab, class: button, text: Add Prefab }
        proportion: 1
      - widget: { id: removeEntity, class: button, text: Remove }
        proportion: 1
  - widget: { id: canvas, class: sceneEditorCanvas }
    proportion: 1
  - widget: { id: entityEditor, class: entityEditor }
...